"""Add constraints to investment models

Revision ID: 542d7fe8cd90
Revises: 0993828ded0a
Create Date: 2025-10-20 10:01:54.198879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542d7fe8cd90'
down_revision = '0993828ded0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
